version: "3"
services:
    web:
        build: .
        environment:
            - "TZ=Europe/Lisbon"
        ports:
            - "8001:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        ports:
        - "1433:1433"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"